### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'data'

### ISSUE THREAD

**Issue by albireox** [sdss/jaeger#47]
```
[ERROR]: Traceback (most recent call last): 
File "moveSingle.py", line 218, in <module> 
asyncio.run(main()) 
File "/Users/csayres/miniconda3/lib/python3.7/asyncio/runners.py", line 43, in run 
return loop.run_until_complete(main) 
File "/Users/csayres/miniconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete 
return future.result() 
File "moveSingle.py", line 173, in main 
await fps.initialise() 
File "/Users/csayres/code/jaeger/python/jaeger/fps.py", line 363, in initialise 
positioner.firmware = get_firmware_command.get_firmware(positioner_id) 
File "/Users/csayres/code/jaeger/python/jaeger/commands/bootloader.py", line 232, in get_firmware 
return format_version(self.get_reply_for_positioner(positioner_id)) 
File "/Users/csayres/code/jaeger/python/jaeger/commands/bootloader.py", line 220, in format_version 
return '.'.join(format(byt, '02d') for byt in reply.data[0:3][::-1]) 
AttributeError: 'bool' object has no attribute 'data'
```

**Comment by albireox** [comment]
This is probably related to #53 but this commit should deal with the exception.
